# Generated by Django 4.1.1 on 2022-11-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField(default='', help_text='This is mardown enabled')),
                ('facebook_url', models.URLField(default='')),
                ('twitter_url', models.URLField(default='')),
                ('linkdn_url', models.URLField(default='')),
                ('instagram_url', models.URLField(default='')),
                ('whatsapp_url', models.URLField(default='')),
                ('youtube_url', models.URLField(default='')),
                ('site_phone1', models.CharField(default='', help_text='Phone number associated with the website.', max_length=25)),
                ('site_phone2', models.CharField(default='', help_text='Phone number associated with the website.', max_length=25)),
                ('site_phone3', models.CharField(default='', help_text='Phone number associated with the website.', max_length=25)),
                ('site_email', models.EmailField(default='fabamall@fabamall.com', max_length=254)),
            ],
        ),
    ]
